package com.parttimejob.enums;

public enum NotificationType {
    APPLICATION_RECEIVED,
    APPLICATION_ACCEPTED,
    APPLICATION_REJECTED,
    APPLICATION_CANCELLED,
    JOB_CANCELLED,
    JOB_COMPLETED,
    PAYMENT_PAID,
    PAYMENT_CONFIRMED,
    REPORT_FILED,
    REPORT_RESOLVED,
    SYSTEM
}
