-- ==============================================================================
-- SAMPLE DATA: PartTime Job Platform
-- Seed data cleared - all accounts and jobs created by users through the app.
-- ==============================================================================
